name: hello-world-ssh

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: greet person
      run: echo "hello world"
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
