name: hello world

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: greet person
      run: echo "hello world"

  greet-2:
    runs-on: ubuntu-latest

    steps:
    - name: greet person
      run: echo "hello world"
