name: ls-before-and-after-uses

on:
  workflow_dispatch:

jobs:
  job-echo-this:
    runs-on: ubuntu-latest

    steps:
    - name: step-ls-before-uses
      run: ls -axl
    - uses: actions/checkout@v2
    - name: ls -axl
      run: ls -axl
      
