name: ls-before-and-after-uses

on:
#  workflow_dispatch:
  [push]
 
jobs:
  job-ls-before-and-after-uses:
    runs-on: ubuntu-latest

    steps:
    - name: ls before uses
      run: ls -axl
    - uses: actions/checkout@v2
    - name: ls after uses
      run: ls -axl
    - name: ls .github after uses
      run: ls .github -axl
    - name: ls .github/workflows after uses
      run: ls .github/workflows -axl
    - name: echo this yml
      run: cat .github/workflows/ls-before-and-after-uses.yml
      
